// <auto-generated />
namespace MVCAplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class atualizeSalesTwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizeSalesTwo));
        
        string IMigrationMetadata.Id
        {
            get { return "201905311904158_atualizeSalesTwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
