// <auto-generated />
namespace MVCAplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class atualizeSalesFour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizeSalesFour));
        
        string IMigrationMetadata.Id
        {
            get { return "201905311952491_atualizeSalesFour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
